### ISSUE TITLE
Error when running Gulp

### ISSUE THREAD

**Issue by t-kelly** [ListnPlay/riot-isomorphic#1]
Receiving the following error when I run gulp:

`Potentially unhandled rejection [3] Error loading "server/index" at C:\Users\Thomas\riot-isomorphic/build/server/index.js
Only file URLs of the form file: allowed running in Node. (WARNING: non-Error used)`

**Comment by t-kelly** [comment]
Solution found at https://github.com/systemjs/systemjs/issues/309

Need to add `'file:' +` before `__dirname` in `gulpfile.js` > `process.env.APP_BASE_PATH`

**Comment by Avnerus** [comment]
Hi,
Thank you for this!
I actually think this can be applied globally in server/environment.js
I commited a fix and tested it on my linux and osx box. Can you tell me if it works on windows?
/Avner

**Comment by t-kelly** [comment]
Ah yeah, that's definitely the smarter fix! Looks good to me. Every running well on my end.

**Comment by Avnerus** [comment]
Ah great!
Thank you
