### ISSUE TITLE
Client mounts main: why?

### ISSUE THREAD

**Issue by michael-simon** [ListnPlay/riot-isomorphic#12]
So the server-side of this app does a text substitution of the main tag with the server-side rendered data. But the client side, for some reason, mounts the 'main' tag as well, despite the fact that it was already rendered (and substituted!) server-side, so there's nothing to change. Is this just to show how you could (or should), is there some other mechanic here I'm missing (to get it to update client-side?), or is it unnecessary? Maybe all three?

**Comment by michael-simon** [comment]
Yeah, it's necessary to get further updates to happen client-side. Nevermind!

**Comment by Avnerus** [comment]
@michael-simon  Right! But while you're here I would suggest to checkout the updated version for Riot3 and more. https://github.com/Avnerus/riot-isomorphic
