### ISSUE TITLE
Is there any way to render nested tags?

### ISSUE THREAD

**Issue by durgesh-priyaranjan** [ListnPlay/riot-isomorphic#5]
This is awesome. But I was curious to know If there is any way to render nested tags.

**Comment by Avnerus** [comment]
Hi,
First of all thank you.
By rendering nested tags, do you mean dynamically mounting them on arbitraty html tags? Afaik that is indeed not supported by server-side Riot. But other than that nested tags are supported and you can dynamically mount/umount them using the `if` statement.
In this project the `<main>` tag has two nested tags: `<mall>` and `<accunt-status>`. The `<mall>` tags dynamically mounts the nested `<apple>` and `<banana>` tags.

**Comment by Avnerus** [comment]
Closing since it's been a week.
