### ISSUE TITLE
What does the application do? >> More info in readme would be great!

### ISSUE THREAD

**Issue by nelsonic** [ListnPlay/riot-isomorphic#8]
What is the app meant to do?
Its unclear from the readme what this app is actually doing...

<img width="494" alt="demo-console-output" src="https://cloud.githubusercontent.com/assets/194400/8755788/58e9f814-2cc5-11e5-8c1f-01ea253eece3.png">

It seems like a disproportionate number of dependencies

<img width="234" alt="insane-number-of-dependencies" src="https://cloud.githubusercontent.com/assets/194400/8755843/c1c947b8-2cc5-11e5-8088-91e2688ced9d.png">

and no tests ...

<img width="812" alt="no-tests" src="https://cloud.githubusercontent.com/assets/194400/8755864/ec8a0a50-2cc5-11e5-9bf7-0e4985b5a74f.png">

This would be a lot more helpful if it was simpler and had tests to help beginners follow along...

**Comment by Avnerus** [comment]
Thanks for the feedback. 
I've added a line in the readme regarding actually browsing to **localhost:3000** to see the project.
The application itself is a kind of fruit marketplace, but that's less relevant since it's more of a boilerplate for a real world isomorphic application.
Sorry I haven't gotten around to write a more elaborate description, but please feel free to ask any specific questions regarding the architecture.
Thanks!

**Comment by nelsonic** [comment]
### Specifics:

We are trying to render our Riot.js Tags (templates) on the server but the `riot.render` method does not do what we expect ...

Why do you have a regular expression in your server `render()` method?

``` js
let view = riot.render(options.mainTag, options.tagOpts);
let regex = new RegExp('<' + options.mainTag + '.*<\/' + options.mainTag + '>');
```

https://github.com/ListnPlay/riot-isomorphic/blob/d1554c75f9df3f2eb4f08287b925e396fe21a218/src/server/index.js#L33-L34

**Comment by Avnerus** [comment]
What do you expect `riot.render` to do?
The `render` function basically mounts a tag onto a string instead of mounting on the browser's DOM.
Then this Regex is used to replace the `<main></main>` string in my index.html template with the result of the render.

**Comment by nelsonic** [comment]
@Avnerus thanks for getting back to us.
Given the server-side example on the Riot.js website: https://muut.com/riotjs/guide/#server-side

<img width="691" alt="riot js-server-side-rendering-instructions-non-existent" src="https://cloud.githubusercontent.com/assets/194400/8751923/51134cc0-2ca8-11e5-95c0-c642b97ef375.png">

Our understanding is that we can simply `require riot`, load the `tag` and then call `riot.render` passing in an object and the output will be html: 

``` js
var riot = require('riot')
var timer = require('timer.tag')

var html = riot.render(timer, { start: 42 })
console.log(html) // <timer><p>Seconds Elapsed: 42</p></timer>
```

But this is _not_ the way it works ... is it?

Relates to: https://github.com/riot/riot/issues/998

**Comment by Avnerus** [comment]
As you can see in this example, the output is indeed the html, but only the html of the `<timer>` tag. And the output goes to the console, not the response object.
For a complete solution, you will have to attach that tag to a complete `<html>` document and send the result back to the client using `res.send` or `res.render`. 
That is what I do in my project.

**Comment by nelsonic** [comment]
Is the `timer.tag` file available somewhere online? 

We tried to simulate this with the following two files:

`hello/hello.tag` see: https://github.com/docdis/learn-riot/blob/04f0cad566d79da50407b05a7871e41399f54fa4/hello/hello.tag

``` html
<hello>
<p>Hello {name}</p>
</hello>
```

`hello/server.js` see: https://github.com/docdis/learn-riot/blob/04f0cad566d79da50407b05a7871e41399f54fa4/hello/server.js

``` js
var riot  = require('riot');
var fs    = require('fs');
var hello = fs.readFileSync(__dirname + '/hello.tag', 'utf8'); // CANNOT require('hello.tag') !!

var html  = riot.render(hello, { name: "Ana" })
console.log(html);
```

We _expect_ the outputted `html` to be **_rendered**_ as:

``` html
<hello>
<p>Hello Ana</p>
</hello>
```

But instead the output of `riot.render` is:

``` html
<<hello>
<p>hello {name}</p>
</hello>
></<hello>
<p>hello {name}</p>
</hello>
>
```

_Why_...? Thanks for your patience in explaining this to us! :+1:

**Comment by Avnerus** [comment]
Personally I don't use .tag files, but I use standard .js files with the `riot.tag` function.
However you _should_ be able to `require('./hello.tag')` (maybe your are missing the `./` ?)
Without requiring the tag it is not compiled and won't work.
You can also try to use `riot.compile` on the file that you read with `fs`.
Which is just what requiring does (https://github.com/riot/riot/blob/master/lib/server/index.js)

**Comment by nelsonic** [comment]
We tried to require the tag: https://github.com/docdis/learn-riot/commit/db46b7431e29f8f6ba57c1ac3f0fac14d2ff4084
But get an error when we try to run it:

```
}.bind(this);
            ^
SyntaxError: Unexpected token ;
```

![cannot-require-riot-tag](https://cloud.githubusercontent.com/assets/194400/8761573/de0c995e-2d4f-11e5-9e40-13d8950b59be.png)

**Comment by Avnerus** [comment]
Hmm..
I ran a little check and noticed that if the entire tag is in one line without newlines it is able to compile it.
But still it doesn't really pass opts. I can look at it further later. As I said I don't have much experience with .tag files. 
You can still use `riot.tag` with server side rendering like in this project.
