### ISSUE TITLE
Why is /build/client/bundle.js 2.2 Megabytes?!

### ISSUE THREAD

**Issue by nelsonic** [ListnPlay/riot-isomorphic#9]
![bundle-js-2 2mb](https://cloud.githubusercontent.com/assets/194400/8760809/b9d3e7da-2d28-11e5-90ec-ae196fac6c62.png)

Why? (_doesn't this defeat the objective of using Riot.js_ ...?)

**Comment by Avnerus** [comment]
I've added the `fullpaths` setting to browserify, so you can now analyze the sizes with [disc](https://github.com/hughsk/disc).
First of all the code is not minified, for that you will need to add an `uglifyify` trasnform in your GulpFile. _(Also if you are worried about network bandwidth you can use gzip)_
Second, I definitely don't think this defeats the purpose of RiotJs.  The fact it is so small, makes it a UI framework that's easy to maintain and understand. It doesn't mean you should only use it for really small applications. This project uses a lot of other packages such as Primus websocket framework, Page client router etc.
